### Create
POST http://192.168.18.11:3000/api/contents
Content-Type: application/json
X-API-KEY: rahasia

{
  "name": "test1",
  "arabic": "test",
  "latin": "test",
  "translate_id": "test"
}

### Get All
GET http://192.168.18.11:3000/api/contents
X-API-KEY: rahasia

### Get
GET http://192.168.18.11:3000/api/contents/76
X-API-KEY: rahasia

### Update
PATCH http://192.168.18.11:3000/api/contents/76
X-API-KEY: rahasia
Content-Type: application/json

{
  "name": "updatedName",
  "arabic": "updatedArabic",
  "latin": "updatedLatin",
  "translate_id": "updatedTranslateId"
}

### Delete
DELETE http://192.168.18.11:3000/api/contents/76
X-API-KEY: rahasia