### Create
POST http://192.168.18.11:3000/api/contents
Content-Type: application/json
X-API-KEY: rahasia

{
  "name": "test",
  "category": "test",
  "arabic": "test",
  "latin": "test",
  "translate_id": "test",
  "description": "test"
}

### Get All
GET http://192.168.18.11:3000/api/contents
X-API-KEY: process.env.API_KEY

### Get
GET http://192.168.18.11:3000/api/contents/76
X-API-KEY: rahasia

### Update
PATCH http://192.168.18.11:3000/api/contents/76
X-API-KEY: rahasia
Content-Type: application/json

{
  "name": "updatedName",
  "category": "updatedCategory",
  "arabic": "updatedArabic",
  "latin": "updatedLatin",
  "translate_id": "updatedTranslateId",
  "description": "updatedDescription"
}

### Delete
DELETE http://192.168.18.11:3000/api/contents/76
X-API-KEY: rahasia